### ISSUE TITLE
After programmer GPIO sample code in MAX32651EVkit. After powering on again, the MCU does not do anything.

### ISSUE THREAD

**Issue by michame951** [analogdevicesinc/msdk#1035]
Hi Sir,
          I used the MAX32625PICO to  programmer GPIO sample code to the MAX32651EVkit. After entering Debug mode, the MCU control buttons and LEDs are work. When I unplugged the USB and plugged it back in, the MCU don't work.
The GPIO sample code path as below.
C:\MaximSDK\Examples\MAX32650\GPIO
![image](https://github.com/analogdevicesinc/msdk/assets/101703394/a320e454-4655-4718-92ab-871af05d2bc7)

I suspect there's something wrong with my Debug Configurations, but I can't see what's wrong.
Could you have any recommands? thanks a lot.
![image](https://github.com/analogdevicesinc/msdk/assets/101703394/f5a54753-3a57-42cb-9071-9ee9ec995866)
![image](https://github.com/analogdevicesinc/msdk/assets/101703394/82bcd086-c563-4318-af1d-325df5007545)
![image](https://github.com/analogdevicesinc/msdk/assets/101703394/f5832557-652b-4b9f-9096-24382984f318)

**Comment by EricB-ADI** [comment]
If you press the reset button does it still work? If it is a problem with power cycling I suspect your linker configuration is putting the code in ram. Can you share the linker configuration?
