### ISSUE TITLE
MAX32665: Bootloader_host and bootloader examples

### ISSUE THREAD

**Issue by marcoramirezcastro** [analogdevicesinc/msdk#1094]
I've noticed the bootloader example projects are located inside the Bluetooth folders on all devices that contain the Bluetooth example directory.

([Bootloader documentation ](https://pdfserv.maximintegrated.com/en/an/ug7637-secure-boot-tools.pdf) points to the `msdk\Examples\MAXxxxxx` examples directory as opposed to the `msdk\Examples\MAXxxxxx\Bluetooth` directory) 

If this is intentional, please disregard.

**Comment by EricB-ADI** [comment]
There are some Bluetooth examples that rely on the bootloader. So it is in that folder to be tightly coupled.
