### ISSUE TITLE
CMSIS DSP Version doesn't match CMSIS & Documentation

### ISSUE THREAD

**Issue by Brandon-Hurst** [analogdevicesinc/msdk#1099]
### Issue
The CMSIS DSP library has been moved to its own repository [Arm-Software/CMSIS-DSP](https://arm-software.github.io/CMSIS-DSP/latest/index.html) outside of the core CMSIS packs since v5.9.0. Currently the MSDK integrates CMSIS 5.9.0, but there is no version given for CMSIS-DSP, which has moved to an independent versioning scheme (starting with v1.10.1). 

### Proposed Fix
The ask here would be to provide some version info for the CMSIS-DSP component that we integrate so that developers can consult the correct documentation.

**Comment by Jake-Carter** [comment]
@Brandon-Hurst just opened a PR to update to `1.16.2` and make the versioning/future updates more transparent
