### ISSUE TITLE
./Libraries/MiscDrivers/PushButton/pb.c PB_Get function doesn't work on AD-APARD32690-SL board

### ISSUE THREAD

**Issue by perkinsmg** [analogdevicesinc/msdk#1156]
The button on the EvKit1 is set up to be high when open, low when closed, so PB_Get works.
But on AD-APARD32690-SL, it's the other way round, and so PB_Get returns when the button is open, not closed.
Of course, you can fix this at the call-site, but it does mean examples don't port nicely from one board to another.

**Comment by Jake-Carter** [comment]
@perkinsmg added the ability to configure the PB polarity and updated the APARD BSP.  

PR open above, branch is [`feat/pb-polarity`](https://github.com/analogdevicesinc/msdk/tree/feat/pb-polarity) if you'd like to test it out
