### ISSUE TITLE
[CMSIS-DSP] How to use latest version of ARM DSP APIs?

### ISSUE THREAD

**Issue by cogito666** [analogdevicesinc/msdk#1162]
Hi there,

I want to use the latest version of ARM CMSIS-DSP APIs on the MAXIM product.
But I don't know if it's possible or not.

As I checked, currently MAXIM SDK relies on CMSIS version 5.9.0.

So my questions are
1) Is there any document/Guide from analogdevice so that developers build/merge/use the latest version of CMSIS-DSP APIs?
2) Is there any plan for analogdevice to merge/test/release new versions of DSP APIs?

**Comment by Jake-Carter** [comment]
@cogito666 PR opened.  The branch is available on [feat/cmsis-dsp-v1-16-2](https://github.com/analogdevicesinc/msdk/tree/feat/cmsis-dsp-v1-16-2) if you'd like to test it early and report any issues.  No project changes are needed to start using the updated version other than building against the branch.

The added version is `1.16.2`, and the new `CMSIS_DSP_VERSION` build option should make future updates more transparent.
