### ISSUE TITLE
BLE RF test returns error 48 when performed RX on S2 phy

### ISSUE THREAD

**Issue by Ankitpatel2022** [analogdevicesinc/msdk#1249]
When tried to run the BLE RF test to receive on S2 phy, it returns error 48.
I think the check [here](https://github.com/analogdevicesinc/msdk/blob/main/Libraries/Cordio/controller/sources/ble/ll/ll_main_dtm.c#L870) needs to be modified `((phy < LL_TEST_PHY_LE_1M) || (phy > LL_TEST_PHY_LE_CODED_S2)) ||`

**Comment by kevin-gillespie** [comment]
I understand the problem you're having, but these parameters are in the specification. You can select LL_TEST_PHY_LE_CODED for S2 and S8 when executing the receiver test. The receiver needs to be able to receive both S2 and S8 when using the Coded PHY.
 
![image](https://github.com/user-attachments/assets/f744cf94-5f6c-4ff7-a247-3d965aa8f666)
