### ISSUE TITLE
Windows11: OpenOCD from MSDK cannot initialize the MAX32625PICO CMSIS-DAP

### ISSUE THREAD

**Issue by rhempel** [analogdevicesinc/msdk#1251]
On my corporate managed Windows11 laptop, the OpenOCD from the MSDK installer will not open the MAX32625PICO CMSIS-DAP device.

On the same laptop, a VirtualBox VM that we attach the same PICO to as a USB device will work under OpenOCD and PyOCD

At this point I'm not sure if it's a general Windows 11 issue, or if it has to do with the corporate management of USB devices - long story short is I can't do any work with the MAX32690FTHR board until this is working.

I can work around it using a Linux laptop but ideally I would like to use a standard (if somewhat locked down) Windows11 device.
 
`Debug: 87 298 semihosting_common.c:109 semihosting_common_init():
Debug: 88 345 cmsis_dap_usb_bulk.c:105 cmsis_dap_usb_open(): could not open device 0x2109:0x0813: Operation not supported or unimplemented on this platform
Debug: 89 345 cmsis_dap_usb_bulk.c:105 cmsis_dap_usb_open(): could not open device 0x27c6:0x63ac: Access denied (insufficient permissions)
Debug: 90 345 cmsis_dap_usb_bulk.c:105 cmsis_dap_usb_open(): could not open device 0x8087:0x0033: Operation not supported or unimplemented on this platform
Debug: 91 361 cmsis_dap_usb_bulk.c:105 cmsis_dap_usb_open(): could not open device 0x8086:0x51ed: Operation not supported or unimplemented on this platform
Debug: 92 361 cmsis_dap_usb_bulk.c:150 cmsis_dap_usb_open(): found product string of 0x0d28:0x0204 'DAPLink CMSIS-DAP'
Debug: 93 371 cmsis_dap_usb_bulk.c:170 cmsis_dap_usb_open(): enumerating interfaces of 0x0d28:0x0204
Debug: 94 377 cmsis_dap_usb_bulk.c:237 cmsis_dap_usb_open(): skipping interface 0, endpoint[0] is not bulk out
Debug: 95 377 cmsis_dap_usb_bulk.c:230 cmsis_dap_usb_open(): skipping interface 1, has only 1 endpoints
Debug: 96 377 cmsis_dap_usb_bulk.c:276 cmsis_dap_usb_open(): skipping interface 2, class 10 subclass 0 protocol 0
Debug: 97 377 cmsis_dap_usb_bulk.c:217 cmsis_dap_usb_open(): found interface 3 string 'CMSIS-DAP v1'
Debug: 98 393 cmsis_dap_usb_bulk.c:237 cmsis_dap_usb_open(): skipping interface 3, endpoint[0] is not bulk out
Debug: 99 393 cmsis_dap_usb_bulk.c:217 cmsis_dap_usb_open(): found interface 4 string 'WebUSB: CMSIS-DAP'
Debug: 100 393 cmsis_dap_usb_bulk.c:230 cmsis_dap_usb_open(): skipping interface 4, has only 0 endpoints
Debug: 101 393 cmsis_dap_usb_bulk.c:105 cmsis_dap_usb_open(): could not open device 0x0c45:0x6d1f: Entity not found
Debug: 102 408 cmsis_dap_usb_bulk.c:105 cmsis_dap_usb_open(): could not open device 0x8086:0x461e: Operation not supported or unimplemented on this platform
Debug: 103 408 cmsis_dap_usb_bulk.c:105 cmsis_dap_usb_open(): could not open device 0x2109:0x2813: Operation not supported or unimplemented on this platform
Debug: 104 408 cmsis_dap_usb_bulk.c:105 cmsis_dap_usb_open(): could not open device 0x0b95:0x1790: Operation not supported or unimplemented on this platform
Error: 105 424 cmsis_dap.c:293 cmsis_dap_open(): unable to find a matching CMSIS-DAP device
Debug: 106 424 command.c:544 run_command(): Command 'init' failed with error code -4`

**Comment by Jake-Carter** [comment]
@rhempel I can confirm that our toolchain should work on Windows 11.  I have been using on my home machine successfully.

The error log seems like permission issues on the USB port.  You will need USB read/write access on the machine to connect to the PICO.  I suspect IT has locked this on your managed machine.  If you can write a file to a USB drive you should have equivalent permissions to connect to the PICO.

The "could not open device" messages are standard as OpenOCD iterates across all the USB devices it can find.  The device ID for the PICO is `0x0d28:0x0204`, which it is finding successfully during the scan.  I've attached a log from my W11 machine for reference.

[win11_connect_log.zip](https://github.com/user-attachments/files/17638681/win11_connect_log.zip)

They key errors in your log are 
- `could not open device 0x27c6:0x63ac: Access denied (insufficient permissions)` - indicating permission issues on a different USB device
- `Error: 105 424 cmsis_dap.c:293 cmsis_dap_open(): unable to find a matching CMSIS-DAP device` - indicating OpenOCD failed to open the device.  This is the same message thrown if there's no PICO connected to your machine either.  Since the scan chain is at least iterating across the end-points I think this further confirms a USB permissions issue.

**Comment by rhempel** [comment]
Thanks for the reply @Jake-Carter - I believe it does have something to do with permissions, but it's not read/write permissions on the USB drive. I have an IT-exception for this on my machine, and I can confirm that I am able to create, read, and modify files on the exposed USB drive for both the DAPLINK and MAINTENANCE modes of the PICO.

I understand how the enumeration scan works for OpenOCD and have looked at the AD fork of the source.

Is there a possibility of adding some additional diagnostic output for the -v option when OpenOCD tries an operation on the  0x0d28:0x0204 device? The enumeration works so there is some other operation failing when it tries to add it to the list of valid CMSIS-DAP devices.

By the way, the command line I am using to open the device is:

`C:\MaximSDK\Tools\OpenOCD\openocd.exe   -f interface\cmsis-dap.cfg -f target\max32690.cfg -d`

**Comment by Jake-Carter** [comment]
Hmm, generally if you can write to a USB drive you shouldn't have any issue with the PICO.

Here are my driver details (Device Manager -> View -> Devices by container -> DAPLink CMSIS-DSP)

Key drivers to check are DAPLINK and WebUSB: CMSIS-DAP.  Do these match?

![image](https://github.com/user-attachments/assets/d554b67e-4765-422e-a735-ee54a2905562)

![image](https://github.com/user-attachments/assets/648cbb88-a79c-4c30-8fbf-c9741dea8ff5)

![image](https://github.com/user-attachments/assets/41a74111-f766-46a1-a860-26c56f7587fb)

![image](https://github.com/user-attachments/assets/5b110bb9-3f4a-427b-b31d-5d15f49e8553)

![image](https://github.com/user-attachments/assets/8511d5a3-e09e-4bd8-9fb4-fe478348bcbd)

**Comment by rhempel** [comment]
The main difference is that I am missing:

- HID compliant vendor-defined device
- USB Input Device

The WebUSB driver I have is slightly different:

![WebUSB Driver](https://github.com/user-attachments/assets/16499d0c-6a6f-4d40-8122-0be68fc4675f)

The Details.txt contents on my PICO are:

```
# DAPLink Firmware - see https://daplink.io
Build ID: v0257-51-gdb95667d (armcc)
Unique ID: 04161701d5b7c84700000000000000000000000097969906
HIC ID: 97969906
Auto Reset: 1
Automation allowed: 1
Overflow detection: 1
Incompatible image detection: 0
Page erasing: 1
Daplink Mode: Interface
Interface Version: 0259
Git SHA: db95667ddf740f77536239782e7b4273c90878cf
Local Mods: 0
USB Interfaces: MSD, CDC, HID, WebUSB
Interface CRC: 0x8ecdbe53
Remount count: 0
URL: http://www.analog.com/max32625pico
```

**Comment by rhempel** [comment]
I have opened a ticket with our IT provider - there are some posts on the web that indicate CrowdStrike may be interfering with some USB endpoint devices. This kind of makes sense, so I'll follow up on this when I hear back ...

**Comment by rhempel** [comment]
Still no update from out IT staff ...

**Comment by rhempel** [comment]
@Jake-Carter UPDATE:

I have looked more closely at the startup logs and there IS one difference - your product string does not match the one I am getting from my PICO.

Here is what I get:

`Debug: 30 139 cmsis_dap_usb_bulk.c:150 cmsis_dap_usb_open(): found product string of 0x0d28:0x0204 '**DAPLink CMSIS-DAP**'

and you have this in your log

`Debug: 96 145 cmsis_dap_usb_bulk.c:150 cmsis_dap_usb_open(): found product string of 0x0d28:0x0204 '**CMSIS-DAP v1**'`

Two things - the line numbers don't match up, so maybe you have a different `openocd.exe` than what is in the MSDK download currently available

Second, the product string does not match, which means my MAX32625PICO probably has different firmware than yours.

Would you be able to point me to a link for the firmware in your PICO and possibly to a link to your openocd.exe (if different from the MSDK build)?

**Comment by rhempel** [comment]
@Jake-Carter - just a follow up, would you be able to point me to a link for the firmware in your PICO?

None of the images PICO firmware repository give the USB Product string in the logs you have shared :-)

**Comment by rhempel** [comment]
@Jake-Carter Here is a little more information from the USB Device Tree Viewer V4.4.3 running on my  Crowdstrike Falcon protected laptop. It looks like the HID descriptor is failing the read operation, which kind of explains why the PICO is not staying on the list of devices that can be opened by OpenOCD

`
        ---------------- Interface Descriptor -----------------
bLength                  : 0x09 (9 bytes)
bDescriptorType          : 0x04 (Interface Descriptor)
bInterfaceNumber         : 0x03 (Interface 3)
bAlternateSetting        : 0x00
bNumEndpoints            : 0x02 (2 Endpoints)
bInterfaceClass          : 0x03 (HID - Human Interface Device)
bInterfaceSubClass       : 0x00 (None)
bInterfaceProtocol       : 0x00 (None)
iInterface               : 0x06 (String Descriptor 6)
 Language 0x0409         : "CMSIS-DAP"
Data (HexDump)           : 09 04 03 00 02 03 00 00 06                        .........

        ------------------- HID Descriptor --------------------
bLength                  : 0x09 (9 bytes)
bDescriptorType          : 0x21 (HID Descriptor)
bcdHID                   : 0x0100 (HID Version 1.00)
bCountryCode             : 0x00 (00 = not localized)
bNumDescriptors          : 0x01
Data (HexDump)           : 09 21 00 01 00 01 22 21 00                        .!...."!.
Descriptor 1:
bDescriptorType          : 0x22 (Class=Report)
wDescriptorLength        : 0x0021 (33 bytes)
**Error reading descriptor : ERROR_GEN_FAILURE (due to a obscure limitation of the Win32 USB API, see F1 Help)**

        ----------------- Endpoint Descriptor -----------------
bLength                  : 0x07 (7 bytes)
bDescriptorType          : 0x05 (Endpoint Descriptor)
bEndpointAddress         : 0x81 (Direction=IN EndpointID=1)
bmAttributes             : 0x03 (TransferType=Interrupt)
wMaxPacketSize           : 0x0040 (64 bytes)
bInterval                : 0x01 (1 ms)
Data (HexDump)           : 07 05 81 03 40 00 01                              ....@..

        ----------------- Endpoint Descriptor -----------------
bLength                  : 0x07 (7 bytes)
bDescriptorType          : 0x05 (Endpoint Descriptor)
bEndpointAddress         : 0x02 (Direction=OUT EndpointID=2)
bmAttributes             : 0x03 (TransferType=Interrupt)
wMaxPacketSize           : 0x0040 (64 bytes)
bInterval                : 0x01 (1 ms)
Data (HexDump)           : 07 05 02 03 40 00 01                              ....@..
`

The F1 Help offers this:

> **About HID descriptors**
> 
> HID descriptors usually cannot be read. This is because they must be requested from the interface rather than the device but the IOCTL_USB_GET_DESCRIPTOR_FROM_NODE_CONNECTION call doesn't offer the choice.
> The parameters are ignored and filled by the USB stack:
> MSDN says: "the USB stack ignores the value of bmRequest and inserts a value of 0x80 which indicates standard USB device request".
> https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/usbioctl/ns-usbioctl-_usb_descriptor_request
> For most devices the result is an ERROR_GEN_FAILURE or ERROR_INVALID_PARAMETER.
> But some devices return the HID descriptor anyway.
>

**Comment by rhempel** [comment]
SOLVED! This turned out to be a lot of digging around and finally stumbling on the solution ...

As an embedded developer I have to support devices from multiple vendors - and that sometimes means installing vendor specific tools and drivers. In this case, I had an old vendor specific CMSIS-DAP v1 driver on my laptop, and this was causing the AD/MAX PICO to pick up the wrong driver.

The fix is relatively simple. Go into Device Manager on your Windows machine and choose "View By Driver". The look for ANY and ALL drivers with CMSIS or DAP in the name, right click, and then choose "Remove Driver"

When you have deleted all of them (and you may have dozens if not hundreds of .inf files) then plug in your MAX32625 PICO and you will be able to use OpenOCD to detect and use the device.

Sometimes you have to keep chewing on the bone ...

![image](https://github.com/user-attachments/assets/9806e542-4c5a-4a78-a651-05d93afa1544)
