### ISSUE TITLE
MAX32666: change to i2c_reva.c creates infinite loop

### ISSUE THREAD

**Issue by JordanAceto** [analogdevicesinc/msdk#1261]
Hi there. We recently updated our MSDK version and found that after the update, calling `MXC_I2C_MasterTransaction()` causes an infinite loop. The calling code was working fine before the update.

The infinite loop is in `i2c_reva.c`, line 997:
https://github.com/analogdevicesinc/msdk/blob/d2480e18f148a307b1e70ce16b07a4d674ff82b9/Libraries/PeriphDrivers/Source/I2C/i2c_reva.c#L997

In the previous version this line used to be:
```c
while (!(i2c->intfl0 & MXC_F_I2C_REVA_INTFL0_STOP)) {}
```

This was changed in commit https://github.com/analogdevicesinc/msdk/commit/79c0d9ae4d7ae85edd9f72fc3fc80f79931ad6d0

Looking at the MAX32666 user guide, it does seem like this change will cause an infinite loop:
![mctl_stop](https://github.com/user-attachments/assets/d939d286-dd27-4068-8728-801cfb6f05b3)

I think what's happening is:

1. `MXC_I2C_RevA_MasterTransaction()` initiates a stop condition in software by writing a 1 to the master control stop bit
2. This bit is immediately cleared by hardware
3. `MXC_I2C_RevA_MasterTransaction()` waits forever for the stop bit to turn into a 1, but it never does

*edited to correct the old line of code which checked for INTFL0 STOP, not INTFL0 DONE as I initially wrote

**Comment by EricB-ADI** [comment]
The fix is merged. Let me know if you need anything else.
