### ISSUE TITLE
Not restarting advertisement after stopped. FreeRTOS tickless

### ISSUE THREAD

**Issue by EdwinFairchild** [analogdevicesinc/msdk#936]
Resuming advertising is not  working once they are stopped. If you comment out line `230` and `239`, essentially remove the if statement and thus the call to `PalBbGetTimestamp` ,  and  keep the if statements contents then it works just fine. 
I think it may be related to accessing the dbb but the `PalBbGetTimestamp` guards against that in the phy by checking `palBbEnableCnt`

https://github.com/analogdevicesinc/msdk/blob/47ac9e535d29921286969f6e486b673ee6ff9d56/Examples/MAX32665/Bluetooth/BLE_FreeRTOS/freertos_tickless.c#L228-L240

### Steps to reproduce:
- Build BLE_FreeRTOS example with tickless mode enabled
- Start application
- Use phone app to see advertising works fine
- [ Button 2 press short ] will stop advertising
- [ Button 1 press short ] will resume advertising (does not resume)

**Comment by EricB-ADI** [comment]
Not having an issue with it.

**Comment by EricB-ADI** [comment]
Removing the if statement basically causes it to never go to sleep.

**Comment by EricB-ADI** [comment]
BB was not being correctly disabled and enabled/restored.
