### ISSUE TITLE
MAX78000FTHR kws20_demo adaption

### ISSUE THREAD

**Issue by Willy0815** [analogdevicesinc/msdk#955]
what are the steps to adapt the kws20_demo, that is predefined for MAX78000 EVKIT? Changing the makefile seems not to be sufficient.

**Comment by Jake-Carter** [comment]
@Willy0815 adapt it for the MAX78000FTHR?

Simply set the BSP to `FTHR_RevA`, then clean and rebuild the project.  See the [MSDK User Guide (Board Support Packages)](https://analogdevicesinc.github.io/msdk//USERGUIDE/#board-support-packages)
