### ISSUE TITLE
MAX32655 Bluetooth examples documentation mix-up

### ISSUE THREAD

**Issue by BaileyBrookes** [analogdevicesinc/msdk#980]
In the "msdk/Examples/MAX32655/Bluetooth/BLE_fit_FreeRTOS/" example, the README.md states that "In the project.mk, changing USE_DUAL_CORE to 1 will enable using both ARM core and RISC-V core for the split HCI.", but there is no such variable in the project.mk

In the "msdk/Examples/MAX32655/Bluetooth/BLE_fit/" example however, the USE_DUAL_CORE is present in its project.mk file but is not mentioned in the examples README.md.

**Comment by EricB-ADI** [comment]
HI @BaileyBrookes , You can add it yourself inside project.mk. The build system, has it defaulted to 0 if it is not present in the project.mk. As far as why it is not there, is most likely legacy.

**Comment by EricB-ADI** [comment]
This is issue has been addressed in #975
